"""v0.2

Revision ID: 31462a7229a9
Revises: 8960d862db45
Create Date: 2021-10-30 00:59:36.238966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31462a7229a9'
down_revision = '8960d862db45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('position', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'position')
    # ### end Alembic commands ###
