"""v0.1

Revision ID: 8960d862db45
Revises: 
Create Date: 2021-10-29 23:47:28.608972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8960d862db45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('bookinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=64), nullable=True),
    sa.Column('introduction', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookinfo_author'), 'bookinfo', ['author'], unique=False)
    op.create_index(op.f('ix_bookinfo_name'), 'bookinfo', ['name'], unique=False)
    op.create_table('librarian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_librarian_name'), 'librarian', ['name'], unique=False)
    op.create_index(op.f('ix_librarian_username'), 'librarian', ['username'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('book',
    sa.Column('barcode', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id_bookinfo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bookinfo'], ['bookinfo.id'], ),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_table('borrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode_book', sa.String(length=128), nullable=True),
    sa.Column('id_use', sa.Integer(), nullable=True),
    sa.Column('start', sa.String(length=32), nullable=True),
    sa.Column('end', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['barcode_book'], ['book.barcode'], ),
    sa.ForeignKeyConstraint(['id_use'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_end'), 'borrow', ['end'], unique=False)
    op.create_index(op.f('ix_borrow_start'), 'borrow', ['start'], unique=False)
    op.create_index(op.f('ix_borrow_status'), 'borrow', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borrow_status'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_start'), table_name='borrow')
    op.drop_index(op.f('ix_borrow_end'), table_name='borrow')
    op.drop_table('borrow')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_librarian_username'), table_name='librarian')
    op.drop_index(op.f('ix_librarian_name'), table_name='librarian')
    op.drop_table('librarian')
    op.drop_index(op.f('ix_bookinfo_name'), table_name='bookinfo')
    op.drop_index(op.f('ix_bookinfo_author'), table_name='bookinfo')
    op.drop_table('bookinfo')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
